# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            backupld
tagline:          'LemonDigits.com'
description:      'A backup framework based on <a href="https://attic-backup.org/" title="Attic">Attic</a>'
url:              //joeasaurus.github.io/backupld
baseurl:          /backupld
production_url:   //joeasaurus.github.io/backupld
BASE_PATH:        //joeasaurus.github.io/backupld

github:
  repo:           //github.com/Joeasaurus/backupld
